// <auto-generated />
using Bank.CardService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bank.CardService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729153146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank.CardService.Models.Entities.Card", b =>
                {
                    b.Property<string>("CardToken")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("CARD_TOKEN");

                    b.Property<string>("CardAccountNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("CARD_ACCOUNT_NO");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)")
                        .HasColumnName("CARD_NO");

                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18)")
                        .HasColumnName("CUSTOMER_ID");

                    b.HasKey("CardToken");

                    b.HasIndex("CardAccountNo")
                        .IsUnique();

                    b.HasIndex("CardNo")
                        .IsUnique();

                    b.ToTable("CARD", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
