// <auto-generated />
using Bank.CustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bank.CustomerService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730063833_AddCustomerIdSequence")]
    partial class AddCustomerIdSequence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("CUSTOMER_ID_SEQ");

            modelBuilder.Entity("Bank.CustomerService.Models.Entities.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SURNAME");

                    b.Property<string>("Tc")
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("TC");

                    b.HasKey("CustomerId");

                    b.ToTable("CUSTOMER", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
