// <auto-generated />
using System;
using Bank.CampaignService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bank.CampaignService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813223316_RemoveBudgetFields")]
    partial class RemoveBudgetFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank.CampaignService.Models.Entities.Campaign", b =>
                {
                    b.Property<long>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("Campaign_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CampaignId"));

                    b.Property<int>("CalculationCriteria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CALCULATION_CRITERIA");

                    b.Property<decimal?>("DailyLimit")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("DAILY_LIMIT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("END_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("Name");

                    b.Property<int>("RewardType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REWARD_TYPE");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("START_DATE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("CampaignId");

                    b.ToTable("CAMPAIGN", (string)null);
                });

            modelBuilder.Entity("Bank.CampaignService.Models.Entities.CampaignCriterion", b =>
                {
                    b.Property<long>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CRITERION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CriterionId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CAMPAIGN_ID");

                    b.Property<bool>("IsFirstTransaction")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_FIRST_TRANSACTION");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("MAX_AMOUNT");

                    b.Property<decimal?>("MinAmount")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("MIN_AMOUNT");

                    b.Property<string>("Otc")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("OTC");

                    b.Property<DateTime?>("TransactionEndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("TRANSACTION_END_DATE");

                    b.Property<DateTime?>("TransactionStartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("TRANSACTION_START_DATE");

                    b.HasKey("CriterionId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CAMPAIGN_CRITERION", (string)null);
                });

            modelBuilder.Entity("Bank.CampaignService.Models.Entities.CampaignCriterion", b =>
                {
                    b.HasOne("Bank.CampaignService.Models.Entities.Campaign", null)
                        .WithMany("Criteria")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bank.CampaignService.Models.Entities.Campaign", b =>
                {
                    b.Navigation("Criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
