<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="10.23.26200" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Bank.Shared\Bank.Shared.csproj" />
  </ItemGroup>
</Project>
