// <auto-generated />
using Bank.PointService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bank.PointService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811114216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("POINT_ACC_NO_SEQ");

            modelBuilder.Entity("Bank.PointService.Models.Entities.PointAccount", b =>
                {
                    b.Property<string>("AccountNo")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("ACCOUNT_NO");

                    b.Property<decimal>("Balance")
                        .HasMaxLength(8)
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("BALANCE");

                    b.Property<long>("CustomerId")
                        .HasMaxLength(18)
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasPrecision(18)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.HasKey("AccountNo");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("POINT_ACCOUNT", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
