// <auto-generated />
using Bank.PointService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bank.PointService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813081032_ChangeColumns")]
    partial class ChangeColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("POINT_ACC_NO_SEQ");

            modelBuilder.Entity("Bank.PointService.Models.Entities.PointAccount", b =>
                {
                    b.Property<string>("AccountNo")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("ACCOUNT_NO");

                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal>("EarnedPoint")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("EARNED_POINT");

                    b.Property<decimal>("ExpiredPoint")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("EXPIRED_POINT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("UsedPoint")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("USED_POINT");

                    b.HasKey("AccountNo");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("POINT_ACCOUNT", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
