// <auto-generated />
using System;
using Bank.AccountService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bank.AccountService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ACCOUNT_NO_SEQ")
                .StartsAt(10000000L);

            modelBuilder.Entity("Bank.AccountService.Models.Entities.Account.Account", b =>
                {
                    b.Property<string>("AccountNo")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("ACCOUNT_NO");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("BALANCE");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("BRANCH_CODE");

                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("STATUS");

                    b.HasKey("AccountNo");

                    b.ToTable("ACCOUNT", (string)null);
                });

            modelBuilder.Entity("Bank.AccountService.Models.Entities.Account.CompletedSagaOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("OPERATION_ID");

                    b.Property<string>("OperationType")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("OPERATION_TYPE");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("COMPLETED_AT");

                    b.HasKey("OperationId", "OperationType");

                    b.ToTable("COMPLETED_SAGA_OPERATIONS", (string)null);
                });

            modelBuilder.Entity("Bank.AccountService.Models.Entities.Limit.ChargeLimit", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal>("AnnualLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("ANNUAL_LIMIT");

                    b.Property<decimal>("DailyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("DAILY_LIMIT");

                    b.Property<decimal>("MonthlyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("MONTHLY_LIMIT");

                    b.HasKey("CustomerId");

                    b.ToTable("CHARGE_LIMITS", (string)null);
                });

            modelBuilder.Entity("Bank.AccountService.Models.Entities.Limit.CurrentChargeLimit", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal>("AnnualLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("ANNUAL_LIMIT");

                    b.Property<decimal>("DailyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("DAILY_LIMIT");

                    b.Property<DateTime>("LastAnnualReset")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_ANNUAL_RESET");

                    b.Property<DateTime>("LastDailyReset")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_DAILY_RESET");

                    b.Property<DateTime>("LastMonthlyReset")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_MONTHLY_RESET");

                    b.Property<decimal>("MonthlyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("MONTHLY_LIMIT");

                    b.HasKey("CustomerId");

                    b.ToTable("CURRENT_CHARGE_LIMITS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
