// <auto-generated />
using System;
using Bank.AuthorizationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bank.AuthorizationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811074058_AddMerchantName")]
    partial class AddMerchantName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank.AuthorizationService.Models.Entities.Authorization", b =>
                {
                    b.Property<string>("Guid")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("GUID");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("ACCOUNT_NO");

                    b.Property<decimal?>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("BALANCE");

                    b.Property<string>("CardToken")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("CARD_TOKEN");

                    b.Property<string>("ChannelCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("CHANNEL_CODE");

                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18,0)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MERCHANT_NAME");

                    b.Property<int>("Otc")
                        .HasPrecision(4)
                        .HasColumnType("NUMBER(4,0)")
                        .HasColumnName("OTC");

                    b.Property<int>("Ots")
                        .HasPrecision(4)
                        .HasColumnType("NUMBER(4,0)")
                        .HasColumnName("OTS");

                    b.Property<decimal?>("TransactionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("TRXN_AMOUNT");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("DATE")
                        .HasColumnName("TRXN_DATE");

                    b.Property<string>("TransactionDescription")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TRXN_DESCRIPTION");

                    b.Property<long>("TransactionId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18,0)")
                        .HasColumnName("TRXN_ID");

                    b.Property<string>("TransactionStatus")
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("TRXN_STATUS");

                    b.HasKey("Guid");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("AUTHORIZATION", (string)null);
                });

            modelBuilder.Entity("Bank.AuthorizationService.Models.Entities.CompletedSagaOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("OPERATION_ID");

                    b.Property<string>("OperationType")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("OPERATION_TYPE");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("COMPLETED_AT");

                    b.HasKey("OperationId", "OperationType");

                    b.ToTable("COMPLETED_SAGA_OPERATIONS", (string)null);
                });

            modelBuilder.Entity("Bank.AuthorizationService.Models.Entities.CurrentSpendingLimit", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal>("AnnualLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("ANNUAL_LIMIT");

                    b.Property<decimal>("DailyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("DAILY_LIMIT");

                    b.Property<DateTime>("LastAnnualReset")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_ANNUAL_RESET");

                    b.Property<DateTime>("LastDailyReset")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_DAILY_RESET");

                    b.Property<DateTime>("LastMonthlyReset")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_MONTHLY_RESET");

                    b.Property<decimal>("MonthlyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("MONTHLY_LIMIT");

                    b.HasKey("CustomerId");

                    b.ToTable("CURRENT_SPENDING_LIMITS", (string)null);
                });

            modelBuilder.Entity("Bank.AuthorizationService.Models.Entities.SpendingLimit", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasPrecision(18)
                        .HasColumnType("NUMBER(18)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal>("AnnualLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("ANNUAL_LIMIT");

                    b.Property<decimal>("DailyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("DAILY_LIMIT");

                    b.Property<decimal>("MonthlyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("MONTHLY_LIMIT");

                    b.HasKey("CustomerId");

                    b.ToTable("SPENDING_LIMITS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
